apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: sonarr
    environment: prod
    type: nfs
  name: prod-sonarr-config
  namespace: servarr
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      app: sonarr
      environment: prod
      type: nfs
  storageClassName: ''
  volumeMode: Filesystem
