apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: qbittorrent
    environment: prod
    type: local
  name: prod-qbittorrent-config
  namespace: servarr
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      app: qbittorrent
      environment: prod
      type: local
  storageClassName: ''
  volumeMode: Filesystem
