apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    app: prowlarr
    environment: prod
    type: local
  name: prod-prowlarr-config-pv
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  storageClassName: ""
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /home/servarr/prowlarr
    type: DirectoryOrCreate
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - node4
