apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    app: prowlarr
    environment: prod
    type: nfs
  name: prod-prowlarr-config-pv
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  nfs:
    path: /mnt/MainPool/k8s-storage/servarr/prowlarr
    server: 10.0.0.200
