apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: prowlarr
    environment: prod
    type: local
  name: prod-prowlarr-config
  namespace: servarr
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      app: prowlarr
      environment: prod
      type: local
  storageClassName: ''
  volumeMode: Filesystem
