apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    app: radarr
    environment: prod
    type: nfs
  name: prod-radarr-config-pv
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 5Gi
  storageClassName: ""
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /mnt/MainPool/k8s-storage/servarr/radarr
    server: 10.0.0.200
