apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: radarr
    environment: prod
    type: nfs
  name: prod-radarr-config
  namespace: servarr
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      app: radarr
      environment: prod
      type: nfs
  storageClassName: ''
  volumeMode: Filesystem
