apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    app: servarr
    environment: prod
    type: nfs
    media-type: tv
  name: prod-media-tv-pv
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 500Gi
  storageClassName: ""
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
  - nfsvers=4
  nfs:
    path: /mnt/MainPool/k8s-storage/servarr/media/tv
    server: 10.0.0.200
