apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: servarr
    environment: prod
    type: nfs
  name: prod-downloads
  namespace: servarr
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
  selector:
    matchLabels:
      app: servarr
      environment: prod
      type: nfs
  storageClassName: ''
  volumeMode: Filesystem
