apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: servarr
    environment: prod
    media-type: anime
  name: prod-media-anime
  namespace: servarr
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 300Gi
  selector:
    matchLabels:
      app: servarr
      environment: prod
      type: nfs
      media-type: anime
