apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    app: bazarr
    environment: prod
    type: nfs
  name: prod-bazarr-config-pv
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 2Gi
  storageClassName: ""
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
  - nfsvers=4.2
  nfs:
    path: /mnt/MainPool/k8s-storage/servarr/bazarr
    server: 10.0.0.200
