apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: bazarr
    environment: prod
    type: local
  name: prod-bazarr-config
  namespace: servarr
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  selector:
    matchLabels:
      app: bazarr
      environment: prod
      type: local
  storageClassName: ''
  volumeMode: Filesystem
