apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    app: lidarr
    environment: prod
    type: nfs
  name: prod-lidarr-config-pv
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  nfs:
    path: /mnt/MainPool/k8s-storage/servarr/lidarr
    server: 10.0.0.200
