apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: lidarr
    environment: prod
    type: nfs
  name: prod-lidarr-config
  namespace: servarr
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      app: lidarr
      environment: prod
      type: nfs
  storageClassName: ''
  volumeMode: Filesystem
