apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    app: lazylibrarian
    environment: prod
    type: nfs
  name: prod-lazylibrarian-config-pv
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 5Gi
  storageClassName: ""
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /mnt/MainPool/k8s-storage/servarr/lazylibrarian
    server: truenas.diagon.ally