apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: jellyseerr
    environment: prod
    type: local
  name: prod-jellyseerr-config
  namespace: servarr
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  selector:
    matchLabels:
      app: jellyseerr
      environment: prod
      type: local
  storageClassName: ''
  volumeMode: Filesystem
